sudo: false
language: python
python:
  - "3.6-dev"

install:
  - pip install .[test]

script:
  - pytest --cov-report term-missing --cov=smartchangelog/

notifications:
  email:

after_success:
  - coveralls
